import{S as u,i as c}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function g(s){const r="https://pixabay.com/api/",o=new URLSearchParams({key:"44427919-32b813221576803201dca5eed",q:s,image_type:"photo",orientation:"horisontal",safesearch:"true",per_page:50}),l=`${r}?${o}`;return fetch(l).then(e=>e.json()).catch(e=>console.log())}function p(s){const{webformatURL:r,largeImageURL:o,tags:l,likes:e,views:t,comments:i,downloads:d}=s;return`<li class="gallery-item">
          <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${r}" alt="${l}" />
            <div class="gallery-describe">
              <p class="gallery-text">Likes <br>${e}</p>
              <p class="gallery-text">Views<br>${t}</p>
              <p class="gallery-text">Comments<br>${i}</p>
              <p class="gallery-text">Downloads<br>${d}</p>
            </div>
          </a>
        </li>`}function f(s){return s.hits.map(p).join("")}const m="/goit-js-hw-11/assets/javascript-61de9f5c.svg",a={galleryElem:document.querySelector(".gallery"),searchBtn:document.querySelector(".search-btn"),formElem:document.querySelector(".search-form"),inputElem:document.querySelector(".search-input"),galleryItem:document.querySelector(".gallery-item"),loader:document.querySelector(".loader")};new u(".gallery a",{captionPosition:"bottom",captionsData:"alt",captionDelay:250});a.formElem.addEventListener("submit",s=>{s.preventDefault(),h();const r=a.inputElem.value.trim();r.length<=0?(c.show({iconUrl:m,title:"Error",titleColor:"white",message:"This field must be filled in",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),n(),a.formElem.reset()):(g(r).then(o=>{if(o.hits.length>0){const l=f(o);a.galleryElem.innerHTML=l,new u(".gallery-item a",{captionsData:"alt",captionDelay:250}).refresh()}else c.show({iconUrl:m,title:"Error",titleColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",theme:"dark"}),n()}).catch(o=>console.log(o)).finally(()=>{n()}),a.formElem.reset())});function h(){a.loader.classList.remove("hidden")}function n(){a.loader.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
